#ifndef CONFIG_FATCRM_VERSION_H
#define CONFIG_FATCRM_VERSION_H

#define FATCRM_VERSION_MAJOR ${FatCRM_VERSION_MAJOR}
#define FATCRM_VERSION_MINOR ${FatCRM_VERSION_MINOR}
#define FATCRM_VERSION_PATCH ${FatCRM_VERSION_PATCH}
#define FATCRM_EXTENDED_STRING "${FatCRM_EXTENDED_VERSION}"

#endif
