#ifndef CONFIG_FATCRM_H
#define CONFIG_FATCRM_H

#cmakedefine FATCRM_VERSION_MAJOR ${FATCRM_VERSION_MAJOR}
#cmakedefine FATCRM_VERSION_MINOR ${FATCRM_VERSION_MINOR}
#cmakedefine FATCRM_VERSION_PATCH ${FATCRM_VERSION_PATCH}
#cmakedefine FATCRM_VERSION_STRING "${FATCRM_VERSION_STRING}"

#endif
