#define FATCRM_VERSION_MAJOR ${FATCRM_VERSION_MAJOR}
#define FATCRM_VERSION_MINOR ${FATCRM_VERSION_MINOR}
#define FATCRM_VERSION_PATCH ${FATCRM_VERSION_PATCH}
#define FATCRM_VERSION_STRING "${FATCRM_VERSION_STRING}"
