
def main():
    startApplication("sugarclient")
    # create a new account and save it
    clickButton(waitForObject(":Form.New Account_QPushButton"))
    type(waitForObject(":Details.name_QLineEdit"), "test account")
    mouseClick(waitForObject(":Details.website_QLineEdit"), 96, 9, 0, Qt.LeftButton)
    type(waitForObject(":Details.website_QLineEdit"), "a web site")
    mouseClick(waitForObject(":Details.tyckerSymbol_QLineEdit"), 92, 14, 0, Qt.LeftButton)
    type(waitForObject(":Details.tyckerSymbol_QLineEdit"), "a ticker")
    type(waitForObject(":Details.tyckerSymbol_QLineEdit"), "<Tab>")
    type(waitForObject(":Details.parentName_QComboBox"), "<Tab>")
    type(waitForObject(":Details.ownership_QLineEdit"), "mine")
    type(waitForObject(":Details.ownership_QLineEdit"), "<Tab>")
    mouseClick(waitForObject(":Details.industry_QComboBox"), 196, 15, 0, Qt.LeftButton)
    mouseClick(waitForObjectItem(":Details.industry_QComboBox", "Apparel"), 101, 10, 0, Qt.LeftButton)
    mouseClick(waitForObject(":Details.accountType_QComboBox"), 190, 14, 0, Qt.LeftButton)
    mouseClick(waitForObjectItem(":Details.accountType_QComboBox", "Analyst"), 114, 8, 0, Qt.LeftButton)
    mouseClick(waitForObject(":Details.assignedUserName_QComboBox"), 192, 12, 0, Qt.LeftButton)
    mouseClick(waitForObjectItem(":Details.assignedUserName_QComboBox", "max"), 134, 11, 0, Qt.LeftButton)
    mouseClick(waitForObject(":Other Details.phoneOffice_QLineEdit"), 76, 17, 0, Qt.LeftButton)
    type(waitForObject(":Other Details.phoneOffice_QLineEdit"), "12345")
    type(waitForObject(":Other Details.phoneOffice_QLineEdit"), "<Tab>")
    type(waitForObject(":Other Details.phoneFax_QLineEdit"), "67890")
    type(waitForObject(":Other Details.phoneFax_QLineEdit"), "<Tab>")
    type(waitForObject(":Other Details.phoneAlternate_QLineEdit"), "09876")
    type(waitForObject(":Other Details.phoneAlternate_QLineEdit"), "<Tab>")
    type(waitForObject(":Other Details.employees_QLineEdit"), "100")
    type(waitForObject(":Other Details.employees_QLineEdit"), "<Tab>")
    type(waitForObject(":Other Details.rating_QLineEdit"), "90")
    type(waitForObject(":Other Details.rating_QLineEdit"), "<Tab>")
    type(waitForObject(":Other Details.sicCode_QLineEdit"), "3333")
    type(waitForObject(":Other Details.sicCode_QLineEdit"), "<Tab>")
    type(waitForObject(":Other Details.annualRevenue_QLineEdit"), "1000000000")
    type(waitForObject(":Other Details.annualRevenue_QLineEdit"), "<Tab>")
    type(waitForObject(":Other Details.email1_QLineEdit"), "mail@kdab.com")
    type(waitForObject(":Other Details.email1_QLineEdit"), "<Tab>")
    type(waitForObject(":Addresses.billingAddressStreet_QLineEdit"), "billing")
    type(waitForObject(":Addresses.billingAddressStreet_QLineEdit"), "<Tab>")
    type(waitForObject(":Addresses.billingAddressCity_QLineEdit"), "Hagfors")
    type(waitForObject(":Addresses.billingAddressCity_QLineEdit"), "<Tab>")
    type(waitForObject(":Addresses.billingAddressState_QLineEdit"), "Värmland")
    type(waitForObject(":Addresses.billingAddressState_QLineEdit"), "<Tab>")
    type(waitForObject(":Addresses.billingAddressPostalcode_QLineEdit"), "34567")
    type(waitForObject(":Addresses.billingAddressPostalcode_QLineEdit"), "<Tab>")
    type(waitForObject(":Addresses.billingAddressCountry_QLineEdit"), "Sweden")
    type(waitForObject(":Addresses.billingAddressCountry_QLineEdit"), "<Tab>")
    type(waitForObject(":Addresses.shippingAddressStreet_QLineEdit"), "shipping")
    type(waitForObject(":Addresses.shippingAddressStreet_QLineEdit"), "<Tab>")
    type(waitForObject(":Addresses.shippingAddressCity_QLineEdit"), "Hagfors")
    type(waitForObject(":Addresses.shippingAddressCity_QLineEdit"), "<Tab>")
    type(waitForObject(":Addresses.shippingAddressState_QLineEdit"), "Värmland")
    type(waitForObject(":Addresses.shippingAddressState_QLineEdit"), "<Tab>")
    type(waitForObject(":Addresses.shippingAddressPostalcode_QLineEdit"), "34567")
    type(waitForObject(":Addresses.shippingAddressPostalcode_QLineEdit"), "<Tab>")
    type(waitForObject(":Addresses.shippingAddressCountry_QLineEdit"), "Sweden")
    type(waitForObject(":Addresses.shippingAddressCountry_QLineEdit"), "<Tab>")
    type(waitForObject(":Description:.description_QTextEdit"), "blä blö blå")
    clickButton(waitForObject(":&Account Details.Save_QPushButton"))
    activateItem(waitForObjectItem(":SugarCRM Client: admin@SugarCRM on localhost.menubar_QMenuBar", "File"))
    activateItem(waitForObjectItem(":SugarCRM Client: admin@SugarCRM on localhost.File_QMenu", "Syncronize"))
    label = waitForObject(':Account Information.admin_QLabel_2')
    waitFor("label.text !=''")
    #data back from remote client - check account's saved data values
    waitFor("object.exists(':Details.website_QLineEdit')")
    test.compare(findObject(":Details.website_QLineEdit").text, "a web site")
    waitFor("object.exists(':Details.tyckerSymbol_QLineEdit')")
    test.compare(findObject(":Details.tyckerSymbol_QLineEdit").text, "a ticker")
    waitFor("object.exists(':Details.parentName_QComboBox')")
    test.compare(findObject(":Details.parentName_QComboBox").currentText, "")    
    waitFor("object.exists(':Details.ownership_QLineEdit')")
    test.compare(findObject(":Details.ownership_QLineEdit").text, "mine")
    waitFor("object.exists(':Details.industry_QComboBox')")
    test.compare(findObject(":Details.industry_QComboBox").currentText, "Apparel")
    waitFor("object.exists(':Details.accountType_QComboBox')")
    test.compare(findObject(":Details.accountType_QComboBox").currentText, "Analyst")    
    waitFor("object.exists(':Details.assignedUserName_QComboBox')")
    test.compare(findObject(":Details.assignedUserName_QComboBox").currentText, "max")    
    waitFor("object.exists(':Other Details.phoneOffice_QLineEdit')")
    test.compare(findObject(":Other Details.phoneOffice_QLineEdit").text, "12345")    
    waitFor("object.exists(':Other Details.phoneFax_QLineEdit')")
    test.compare(findObject(":Other Details.phoneFax_QLineEdit").text, "67890")    
    waitFor("object.exists(':Other Details.phoneAlternate_QLineEdit')")
    test.compare(findObject(":Other Details.phoneAlternate_QLineEdit").text, "09876")    
    waitFor("object.exists(':Other Details.employees_QLineEdit')")
    test.compare(findObject(":Other Details.employees_QLineEdit").text, "100")    
    waitFor("object.exists(':Other Details.rating_QLineEdit')")
    test.compare(findObject(":Other Details.rating_QLineEdit").text, "90")    
    waitFor("object.exists(':Other Details.sicCode_QLineEdit')")
    test.compare(findObject(":Other Details.sicCode_QLineEdit").text, "3333")    
    waitFor("object.exists(':Other Details.annualRevenue_QLineEdit')")
    test.compare(findObject(":Other Details.annualRevenue_QLineEdit").text, "1000000000")    
    waitFor("object.exists(':Other Details.email1_QLineEdit')")
    test.compare(findObject(":Other Details.email1_QLineEdit").text, "mail@kdab.com")    
    waitFor("object.exists(':Addresses.billingAddressStreet_QLineEdit')")
    test.compare(findObject(":Addresses.billingAddressStreet_QLineEdit").text, "billing")    
    waitFor("object.exists(':Addresses.billingAddressCity_QLineEdit')")
    test.compare(findObject(":Addresses.billingAddressCity_QLineEdit").text, "Hagfors")    
    waitFor("object.exists(':Addresses.billingAddressState_QLineEdit')")
    test.compare(findObject(":Addresses.billingAddressState_QLineEdit").text, "Värmland")    
    waitFor("object.exists(':Addresses.billingAddressPostalcode_QLineEdit')")
    test.compare(findObject(":Addresses.billingAddressPostalcode_QLineEdit").text, "34567")
    waitFor("object.exists(':Addresses.billingAddressCountry_QLineEdit')")
    test.compare(findObject(":Addresses.billingAddressCountry_QLineEdit").text, "Sweden")
    waitFor("object.exists(':Addresses.shippingAddressStreet_QLineEdit')")
    test.compare(findObject(":Addresses.shippingAddressStreet_QLineEdit").text, "shipping")
    waitFor("object.exists(':Addresses.shippingAddressCity_QLineEdit')")
    test.compare(findObject(":Addresses.shippingAddressCity_QLineEdit").text, "Hagfors")
    waitFor("object.exists(':Addresses.shippingAddressState_QLineEdit')")
    test.compare(findObject(":Addresses.shippingAddressState_QLineEdit").text, "Värmland")
    waitFor("object.exists(':Addresses.shippingAddressPostalcode_QLineEdit')")
    test.compare(findObject(":Addresses.shippingAddressPostalcode_QLineEdit").text, "34567")
    waitFor("object.exists(':Addresses.shippingAddressCountry_QLineEdit')")
    test.compare(findObject(":Addresses.shippingAddressCountry_QLineEdit").text, "Sweden")
    waitFor("object.exists(':Description:.description_QTextEdit')")
    test.compare(findObject(":Description:.description_QTextEdit").plainText, "blä blö blå")
    clickButton(waitForObject(":SugarCRM Client: admin@SugarCRM on localhost.Show Details_QCheckBox"))
    mouseClick(waitForObject(":Form.searchLE_QLineEdit"), 71, 15, 0, Qt.LeftButton)
    type(waitForObject(":Form.searchLE_QLineEdit"), "hello")
    type(waitForObject(":Form.searchLE_QLineEdit"), "<Backspace>")
    type(waitForObject(":Form.searchLE_QLineEdit"), "<Backspace>")
    type(waitForObject(":Form.searchLE_QLineEdit"), "<Backspace>")
    type(waitForObject(":Form.searchLE_QLineEdit"), "<Backspace>")
    type(waitForObject(":Form.searchLE_QLineEdit"), "<Backspace>")
    clickButton(waitForObject(":SugarCRM Client: admin@SugarCRM on localhost.Show Details_QCheckBox"))
    # create and save a new Opportunity
    clickTab(waitForObject(":SugarCRM Client: admin@SugarCRM on localhost.qt_tabwidget_tabbar_QTabBar"), "Opportunities")
    clickButton(waitForObject(":Form.New Opportunity_QPushButton"))
    type(waitForObject(":Details.name_QLineEdit_2"), "test opportunity")
    type(waitForObject(":Details.name_QLineEdit_2"), "<Tab>")
    mouseClick(waitForObject(":Details.accountName_QComboBox"), 75, 5, 0, Qt.LeftButton)
    mouseClick(waitForObjectItem(":Details.accountName_QComboBox", "test account"), 86, 4, 0, Qt.LeftButton)
    mouseClick(waitForObjectItem(":Details.opportunityType_QComboBox", "Existing Business"), 83, 7, 0, Qt.LeftButton)
    mouseClick(waitForObjectItem(":Details.leadSource_QComboBox", "Cold Call"), 72, 5, 0, Qt.LeftButton)
    mouseClick(waitForObject(":Details.campaignName_QComboBox_2"), 75, 12, 0, Qt.LeftButton)
    mouseClick(waitForObjectItem(":Details.salesStage_QComboBox", "Prospecting"), 42, 10, 0, Qt.LeftButton)
    mouseClick(waitForObjectItem(":Details.assignedUserName_QComboBox_2", "max"), 68, 12, 0, Qt.LeftButton)
    mouseClick(waitForObject(":Other Details.currency_QComboBox"), 40, 8, 0, Qt.LeftButton)
    mouseClick(waitForObjectItem(":Other Details.currency_QComboBox", "US Dollars : $"), 37, 3, 0, Qt.LeftButton)
    mouseClick(waitForObject(":Other Details.amount_QLineEdit"), 44, 8, 0, Qt.LeftButton)
    type(waitForObject(":Other Details.amount_QLineEdit"), "1234567")
    clickButton(waitForObject(":Other Details.Edit_EditCalendarButton"))
    waitForObjectItem(":Calendar.qt_calendar_calendarview_QCalendarView", "1/2")
    clickItem(":Calendar.qt_calendar_calendarview_QCalendarView", "1/2", 15, 15, 0, Qt.LeftButton)
    mouseClick(waitForObject(":Other Details.nextStep_QLineEdit"), 98, 17, 0, Qt.LeftButton)
    type(waitForObject(":Other Details.nextStep_QLineEdit"), "another step")
    mouseClick(waitForObject(":Other Details.probability_QLineEdit"), 74, 15, 0, Qt.LeftButton)
    type(waitForObject(":Other Details.probability_QLineEdit"), "90.9999")
    mouseClick(waitForObject(":Description:.description_QTextEdit_2"), 500, 21, 0, Qt.LeftButton)
    type(waitForObject(":Description:.description_QTextEdit_2"), "ö ä å ")
    clickButton(waitForObject(":&Opportunity Details.Save_QPushButton"))
    activateItem(waitForObjectItem(":SugarCRM Client: admin@SugarCRM on localhost.menubar_QMenuBar", "File"))
    activateItem(waitForObjectItem(":SugarCRM Client: admin@SugarCRM on localhost.File_QMenu", "Syncronize"))
    label = waitForObject(':Opportunity Information.createdBy_QLabel')
    waitFor("label.text !=''")
    #data back from remote client - check opportunity's saved data values    
    waitFor("object.exists(':Details.name_QLineEdit_2')")
    test.compare(findObject(":Details.name_QLineEdit_2").text, "test opportunity")    
    waitFor("object.exists(':Details.accountName_QComboBox')")
    test.compare(findObject(":Details.accountName_QComboBox").currentText, "test account")    
    waitFor("object.exists(':Details.opportunityType_QComboBox')")
    test.compare(findObject(":Details.opportunityType_QComboBox").currentText, "Existing Business")    
    waitFor("object.exists(':Details.leadSource_QComboBox')")
    test.compare(findObject(":Details.leadSource_QComboBox").currentText, "Cold Call")    
    waitFor("object.exists(':Details.salesStage_QComboBox')")
    test.compare(findObject(":Details.salesStage_QComboBox").currentText, "Prospecting")    
    waitFor("object.exists(':Details.assignedUserName_QComboBox_2')")
    test.compare(findObject(":Details.assignedUserName_QComboBox_2").currentText, "max")
    waitFor("object.exists(':Other Details.currency_QComboBox')")
    test.compare(findObject(":Other Details.currency_QComboBox").currentText, "US Dollars : $")
    waitFor("object.exists(':Other Details.amount_QLineEdit')")
    test.compare(findObject(":Other Details.amount_QLineEdit").text, "1234567")
    waitFor("object.exists(':Other Details.dateClosed_QLineEdit')")
    test.compare(findObject(":Other Details.dateClosed_QLineEdit").text, "2010-06-28")    
    waitFor("object.exists(':Other Details.nextStep_QLineEdit')")
    test.compare(findObject(":Other Details.nextStep_QLineEdit").text, "another step")    
    waitFor("object.exists(':Other Details.probability_QLineEdit')")
    test.compare(findObject(":Other Details.probability_QLineEdit").text, "90.9999")
    waitFor("object.exists(':Description:.description_QTextEdit_2')")
    test.compare(findObject(":Description:.description_QTextEdit_2").plainText, "ö ä å ")
    clickButton(waitForObject(":SugarCRM Client: admin@SugarCRM on localhost.Show Details_QCheckBox"))
    mouseClick(waitForObject(":Form.searchLE_QLineEdit_2"), 36, 17, 0, Qt.LeftButton)
    type(waitForObject(":Form.searchLE_QLineEdit_2"), "hello")
    type(waitForObject(":Form.searchLE_QLineEdit_2"), "<Backspace>")
    type(waitForObject(":Form.searchLE_QLineEdit_2"), "<Backspace>")
    type(waitForObject(":Form.searchLE_QLineEdit_2"), "<Backspace>")
    type(waitForObject(":Form.searchLE_QLineEdit_2"), "<Backspace>")
    type(waitForObject(":Form.searchLE_QLineEdit_2"), "<Backspace>")
    clickButton(waitForObject(":SugarCRM Client: admin@SugarCRM on localhost.Show Details_QCheckBox"))
    clickTab(waitForObject(":SugarCRM Client: admin@SugarCRM on localhost.qt_tabwidget_tabbar_QTabBar"), "Leads")
    clickButton(waitForObject(":Form.New Lead_QPushButton"))
    # create and save a new Lead
    mouseClick(waitForObject(":Details.leadSource_QComboBox_2"), 137, 12, 0, Qt.LeftButton)
    mouseClick(waitForObjectItem(":Details.leadSource_QComboBox_2", "Self Generated"), 103, 7, 0, Qt.LeftButton)
    mouseClick(waitForObject(":Details.leadSourceDescription_QTextEdit"), 101, 41, 0, Qt.LeftButton)
    type(waitForObject(":Details.leadSourceDescription_QTextEdit"), "a description")
    mouseClick(waitForObject(":Details.referedBy_QLineEdit"), 63, 15, 0, Qt.LeftButton)
    type(waitForObject(":Details.referedBy_QLineEdit"), "michel")
    mouseClick(waitForObject(":Details.salutation_QComboBox"), 64, 17, 0, Qt.LeftButton)
    mouseClick(waitForObjectItem(":Details.salutation_QComboBox", "Ms\\."), 40, 10, 0, Qt.LeftButton)
    mouseClick(waitForObject(":Details.firstName_QLineEdit"), 22, 15, 0, Qt.LeftButton)
    type(waitForObject(":Details.firstName_QLineEdit"), "Piggy")
    mouseClick(waitForObject(":Details.lastName_QLineEdit"), 95, 4, 0, Qt.LeftButton)
    type(waitForObject(":Details.lastName_QLineEdit"), "helli")
    clickButton(waitForObject(":Details.Edit_EditCalendarButton"))
    waitForObjectItem(":Calendar.qt_calendar_calendarview_QCalendarView", "2/2")
    clickItem(":Calendar.qt_calendar_calendarview_QCalendarView", "2/2", 13, 6, 0, Qt.LeftButton)
    mouseClick(waitForObject(":Details.accountName_QLineEdit"), 51, 16, 0, Qt.LeftButton)
    type(waitForObject(":Details.accountName_QLineEdit"), "test account")
    mouseClick(waitForObject(":Details.title_QLineEdit"), 59, 9, 0, Qt.LeftButton)
    type(waitForObject(":Details.title_QLineEdit"), "ceo")
    mouseClick(waitForObject(":Details.department_QLineEdit"), 64, 8, 0, Qt.LeftButton)
    type(waitForObject(":Details.department_QLineEdit"), "sales")
    mouseClick(waitForObject(":Details.assignedUserName_QComboBox_3"), 63, 7, 0, Qt.LeftButton)
    mouseClick(waitForObjectItem(":Details.assignedUserName_QComboBox_3", "max"), 42, 2, 0, Qt.LeftButton)
    mouseClick(waitForObject(":Other Details.status_QComboBox"), 75, 13, 0, Qt.LeftButton)
    mouseClick(waitForObjectItem(":Other Details.status_QComboBox", "In Process"), 51, 4, 0, Qt.LeftButton)
    mouseClick(waitForObject(":Other Details.statusDescription_QTextEdit"), 58, 35, 0, Qt.LeftButton)
    type(waitForObject(":Other Details.statusDescription_QTextEdit"), "a status description")
    mouseClick(waitForObject(":Other Details.opportunityAmount_QLineEdit"), 53, 16, 0, Qt.LeftButton)
    type(waitForObject(":Other Details.opportunityAmount_QLineEdit"), "9087654")
    mouseClick(waitForObject(":Other Details.phoneWork_QLineEdit"), 59, 10, 0, Qt.LeftButton)
    type(waitForObject(":Other Details.phoneWork_QLineEdit"), "7890")
    mouseClick(waitForObject(":Other Details.phoneMobile_QLineEdit"), 56, 8, 0, Qt.LeftButton)
    type(waitForObject(":Other Details.phoneMobile_QLineEdit"), "0987")
    mouseClick(waitForObject(":Other Details.phoneHome_QLineEdit"), 56, 15, 0, Qt.LeftButton)
    type(waitForObject(":Other Details.phoneHome_QLineEdit"), "23456")
    mouseClick(waitForObject(":Other Details.phoneOther_QLineEdit"), 65, 17, 0, Qt.LeftButton)
    type(waitForObject(":Other Details.phoneOther_QLineEdit"), "65432")
    mouseClick(waitForObject(":Other Details.phoneFax_QLineEdit_2"), 60, 15, 0, Qt.LeftButton)
    type(waitForObject(":Other Details.phoneFax_QLineEdit_2"), "12345")
    mouseClick(waitForObject(":Other Details.email1_QLineEdit_2"), 65, 17, 0, Qt.LeftButton)
    type(waitForObject(":Other Details.email1_QLineEdit_2"), "mail1@mail.com")
    mouseClick(waitForObject(":Other Details.email2_QLineEdit"), 44, 10, 0, Qt.LeftButton)
    type(waitForObject(":Other Details.email2_QLineEdit"), "mail2@mail.com")
    mouseClick(waitForObject(":Addresses.primaryAddressStreet_QLineEdit"), 42, 13, 0, Qt.LeftButton)
    type(waitForObject(":Addresses.primaryAddressStreet_QLineEdit"), "primary")
    type(waitForObject(":Addresses.primaryAddressStreet_QLineEdit"), "<Tab>")
    type(waitForObject(":Addresses.primaryAddressCity_QLineEdit"), "Hagfors")
    type(waitForObject(":Addresses.primaryAddressCity_QLineEdit"), "<Tab>")
    type(waitForObject(":Addresses.primaryAddressState_QLineEdit"), "Värmland")
    type(waitForObject(":Addresses.primaryAddressState_QLineEdit"), "<Tab>")
    type(waitForObject(":Addresses.primaryAddressPostalcode_QLineEdit"), "23456")
    type(waitForObject(":Addresses.primaryAddressPostalcode_QLineEdit"), "<Tab>")
    type(waitForObject(":Addresses.primaryAddressCountry_QLineEdit"), "Sweden")
    type(waitForObject(":Addresses.primaryAddressCountry_QLineEdit"), "<Tab>")
    type(waitForObject(":Addresses.altAddressStreet_QLineEdit"), "other address")
    type(waitForObject(":Addresses.altAddressStreet_QLineEdit"), "<Tab>")
    type(waitForObject(":Addresses.altAddressCity_QLineEdit"), "Hagfors")
    type(waitForObject(":Addresses.altAddressCity_QLineEdit"), "<Tab>")
    type(waitForObject(":Addresses.altAddressState_QLineEdit"), "Värmland")
    type(waitForObject(":Addresses.altAddressState_QLineEdit"), "<Tab>")
    type(waitForObject(":Addresses.altAddressPostalcode_QLineEdit"), "23456")
    type(waitForObject(":Addresses.altAddressPostalcode_QLineEdit"), "<Tab>")
    type(waitForObject(":Addresses.altAddressCountry_QLineEdit"), "Sweden")
    mouseClick(waitForObject(":Description:.description_QTextEdit_3"), 216, 23, 0, Qt.LeftButton)
    type(waitForObject(":Description:.description_QTextEdit_3"), "klöä åpoiu äåäö")
    clickButton(waitForObject(":&Lead Details.Save_QPushButton"))
    activateItem(waitForObjectItem(":SugarCRM Client: admin@SugarCRM on localhost.menubar_QMenuBar", "File"))
    activateItem(waitForObjectItem(":SugarCRM Client: admin@SugarCRM on localhost.File_QMenu", "Syncronize"))
    label = waitForObject(':Lead Information.createdBy_QLabel')
    waitFor("label.text !=''")
    #data back from remote client - check Lead's saved data values    
    waitFor("object.exists(':Details.leadSource_QComboBox_2')")
    test.compare(findObject(":Details.leadSource_QComboBox_2").currentText, "Self Generated")
    waitFor("object.exists(':Details.leadSourceDescription_QTextEdit')")
    test.compare(findObject(":Details.leadSourceDescription_QTextEdit").plainText, "a description")    
    waitFor("object.exists(':Details.referedBy_QLineEdit')")
    test.compare(findObject(":Details.referedBy_QLineEdit").text, "michel")
    waitFor("object.exists(':Details.salutation_QComboBox')")
    test.compare(findObject(":Details.salutation_QComboBox").currentText, "Ms.")    
    waitFor("object.exists(':Details.firstName_QLineEdit')")
    test.compare(findObject(":Details.firstName_QLineEdit").text, "Piggy")
    waitFor("object.exists(':Details.lastName_QLineEdit')")
    test.compare(findObject(":Details.lastName_QLineEdit").text, "helli")    
    waitFor("object.exists(':Details.birthdate_QLineEdit_2')")
    test.compare(findObject(":Details.birthdate_QLineEdit_2").text, "2010-07-05")       
    waitFor("object.exists(':Details.accountName_QLineEdit')")
    test.compare(findObject(":Details.accountName_QLineEdit").text, "test account")    
    waitFor("object.exists(':Details.title_QLineEdit')")
    test.compare(findObject(":Details.title_QLineEdit").text, "ceo")    
    waitFor("object.exists(':Details.department_QLineEdit')")
    test.compare(findObject(":Details.department_QLineEdit").text, "sales")
    waitFor("object.exists(':Details.assignedUserName_QComboBox_3')")
    test.compare(findObject(":Details.assignedUserName_QComboBox_3").currentText, "max")    
    waitFor("object.exists(':Other Details.status_QComboBox')")
    test.compare(findObject(":Other Details.status_QComboBox").currentText, "In Process")    
    waitFor("object.exists(':Other Details.statusDescription_QTextEdit')")
    test.compare(findObject(":Other Details.statusDescription_QTextEdit").plainText, "a status description")
    waitFor("object.exists(':Other Details.opportunityAmount_QLineEdit')")
    test.compare(findObject(":Other Details.opportunityAmount_QLineEdit").text, "9087654")
    waitFor("object.exists(':Other Details.phoneWork_QLineEdit')")
    test.compare(findObject(":Other Details.phoneWork_QLineEdit").text, "7890")
    waitFor("object.exists(':Other Details.phoneMobile_QLineEdit')")
    test.compare(findObject(":Other Details.phoneMobile_QLineEdit").text, "0987")
    waitFor("object.exists(':Other Details.phoneHome_QLineEdit')")
    test.compare(findObject(":Other Details.phoneHome_QLineEdit").text, "23456")
    waitFor("object.exists(':Other Details.phoneOther_QLineEdit')")
    test.compare(findObject(":Other Details.phoneOther_QLineEdit").text, "65432")
    waitFor("object.exists(':Other Details.phoneFax_QLineEdit_2')")
    test.compare(findObject(":Other Details.phoneFax_QLineEdit_2").text, "12345")
    waitFor("object.exists(':Other Details.email1_QLineEdit_2')")
    test.compare(findObject(":Other Details.email1_QLineEdit_2").text, "mail1@mail.com")
    waitFor("object.exists(':Other Details.email2_QLineEdit')")
    test.compare(findObject(":Other Details.email2_QLineEdit").text, "mail2@mail.com")
    waitFor("object.exists(':Addresses.primaryAddressStreet_QLineEdit')")
    test.compare(findObject(":Addresses.primaryAddressStreet_QLineEdit").text, "primary")
    waitFor("object.exists(':Addresses.primaryAddressCity_QLineEdit')")
    test.compare(findObject(":Addresses.primaryAddressCity_QLineEdit").text, "Hagfors")
    waitFor("object.exists(':Addresses.primaryAddressState_QLineEdit')")
    test.compare(findObject(":Addresses.primaryAddressState_QLineEdit").text, "Värmland")
    waitFor("object.exists(':Addresses.primaryAddressPostalcode_QLineEdit')")
    test.compare(findObject(":Addresses.primaryAddressPostalcode_QLineEdit").text, "23456")
    waitFor("object.exists(':Addresses.primaryAddressCountry_QLineEdit')")
    test.compare(findObject(":Addresses.primaryAddressCountry_QLineEdit").text, "Sweden")
    waitFor("object.exists(':Addresses.altAddressStreet_QLineEdit')")
    test.compare(findObject(":Addresses.altAddressStreet_QLineEdit").text, "other address")
    waitFor("object.exists(':Addresses.altAddressCity_QLineEdit')")
    test.compare(findObject(":Addresses.altAddressCity_QLineEdit").text, "Hagfors")
    waitFor("object.exists(':Addresses.altAddressState_QLineEdit')")
    test.compare(findObject(":Addresses.altAddressState_QLineEdit").text, "Värmland")
    waitFor("object.exists(':Addresses.altAddressPostalcode_QLineEdit')")
    test.compare(findObject(":Addresses.altAddressPostalcode_QLineEdit").text, "23456")    
    waitFor("object.exists(':Addresses.altAddressCountry_QLineEdit')")
    test.compare(findObject(":Addresses.altAddressCountry_QLineEdit").text, "Sweden")
    waitFor("object.exists(':Description:.description_QTextEdit_3')")
    test.compare(findObject(":Description:.description_QTextEdit_3").plainText, "klöä åpoiu äåäö")  
    mouseClick(waitForObject(":Form.searchLE_QLineEdit_3"), 73, 7, 0, Qt.LeftButton)
    clickButton(waitForObject(":SugarCRM Client: admin@SugarCRM on localhost.Show Details_QCheckBox"))
    mouseClick(waitForObject(":Form.searchLE_QLineEdit_3"), 44, 13, 0, Qt.LeftButton)
    type(waitForObject(":Form.searchLE_QLineEdit_3"), "abba")
    type(waitForObject(":Form.searchLE_QLineEdit_3"), "<Backspace>")
    type(waitForObject(":Form.searchLE_QLineEdit_3"), "<Backspace>")
    type(waitForObject(":Form.searchLE_QLineEdit_3"), "<Backspace>")
    type(waitForObject(":Form.searchLE_QLineEdit_3"), "<Backspace>")
    type(waitForObject(":Form.searchLE_QLineEdit_3"), "test")
    mouseClick(waitForObject(":Form.searchLE_QLineEdit_3"), 44, 13, 0, Qt.LeftButton)
    waitForObjectItem(":Form.leadsTV_Akonadi::EntityTreeView", "In Process")
    clickItem(":Form.leadsTV_Akonadi::EntityTreeView", "In Process", 23, 8, 0, Qt.LeftButton)
    clickButton(waitForObject(":SugarCRM Client: admin@SugarCRM on localhost.Show Details_QCheckBox"))
    clickTab(waitForObject(":SugarCRM Client: admin@SugarCRM on localhost.qt_tabwidget_tabbar_QTabBar"), "Contacts")
    # create and save a new Contact
    clickButton(waitForObject(":Contacts.New Contact_QPushButton"))
    mouseClick(waitForObject(":Details.salutation_QComboBox_2"), 57, 14, 0, Qt.LeftButton)
    mouseClick(waitForObjectItem(":Details.salutation_QComboBox_2", "Mr\\."), 54, 12, 0, Qt.LeftButton)
    mouseClick(waitForObject(":Details.firstName_QLineEdit_2"), 55, 11, 0, Qt.LeftButton)
    type(waitForObject(":Details.firstName_QLineEdit_2"), "test")
    mouseClick(waitForObject(":Details.lastName_QLineEdit_2"), 53, 10, 0, Qt.LeftButton)
    type(waitForObject(":Details.lastName_QLineEdit_2"), "contact")
    mouseClick(waitForObject(":Details.title_QLineEdit_2"), 18, 14, 0, Qt.LeftButton)
    type(waitForObject(":Details.title_QLineEdit_2"), "vd")
    type(waitForObject(":Details.title_QLineEdit_2"), "<Tab>")
    type(waitForObject(":Details.department_QLineEdit_2"), "sales")
    mouseClick(waitForObject(":Details.accountName_QComboBox_2"), 132, 14, 0, Qt.LeftButton)
    mouseClick(waitForObjectItem(":Details.accountName_QComboBox_2", "test account"), 107, 8, 0, Qt.LeftButton)
    mouseClick(waitForObject(":Details.leadSource_QComboBox_3"), 111, 18, 0, Qt.LeftButton)
    mouseClick(waitForObjectItem(":Details.leadSource_QComboBox_3", "Employee"), 91, 5, 0, Qt.LeftButton)
    mouseClick(waitForObject(":Details.assignedTo_QComboBox"), 78, 15, 0, Qt.LeftButton)
    mouseClick(waitForObjectItem(":Details.assignedTo_QComboBox", "will"), 51, 10, 0, Qt.LeftButton)
    mouseClick(waitForObject(":Details.assignedTo_QComboBox"), 94, 14, 0, Qt.LeftButton)
    mouseClick(waitForObjectItem(":Details.assignedTo_QComboBox", "max"), 57, 6, 0, Qt.LeftButton)
    mouseClick(waitForObjectItem(":Details.reportsTo_QComboBox", "Lynn Ahl"), 47, 3, 0, Qt.LeftButton)
    mouseClick(waitForObject(":Details.primaryEmail_QLineEdit"), 49, 7, 0, Qt.LeftButton)
    type(waitForObject(":Details.primaryEmail_QLineEdit"), "mail@kdab.com")
    mouseClick(waitForObject(":Other Details.officePhone_QLineEdit"), 30, 7, 0, Qt.LeftButton)
    type(waitForObject(":Other Details.officePhone_QLineEdit"), "123456")
    mouseClick(waitForObject(":Other Details.mobilePhone_QLineEdit"), 34, 13, 0, Qt.LeftButton)
    type(waitForObject(":Other Details.mobilePhone_QLineEdit"), "654321")
    mouseClick(waitForObject(":Other Details.homePhone_QLineEdit"), 40, 9, 0, Qt.LeftButton)
    type(waitForObject(":Other Details.homePhone_QLineEdit"), "78906")
    mouseClick(waitForObject(":Other Details.otherPhone_QLineEdit"), 45, 9, 0, Qt.LeftButton)
    type(waitForObject(":Other Details.otherPhone_QLineEdit"), "234567")
    mouseClick(waitForObject(":Other Details.fax_QLineEdit"), 44, 13, 0, Qt.LeftButton)
    type(waitForObject(":Other Details.fax_QLineEdit"), "876543")
    clickButton(waitForObject(":Other Details.Edit_EditCalendarButton_2"))
    waitForObjectItem(":Calendar.qt_calendar_calendarview_QCalendarView", "2/2")
    clickItem(":Calendar.qt_calendar_calendarview_QCalendarView", "2/2", 20, 9, 0, Qt.LeftButton)
    mouseClick(waitForObject(":Other Details.assistant_QLineEdit"), 74, 12, 0, Qt.LeftButton)
    type(waitForObject(":Other Details.assistant_QLineEdit"), "mrs untel")
    mouseClick(waitForObject(":Other Details.assistantPhone_QLineEdit"), 77, 8, 0, Qt.LeftButton)
    type(waitForObject(":Other Details.assistantPhone_QLineEdit"), "876590")
    mouseClick(waitForObject(":Addresses.primaryAddress_QLineEdit"), 51, 20, 0, Qt.LeftButton)
    type(waitForObject(":Addresses.primaryAddress_QLineEdit"), "primary")
    type(waitForObject(":Addresses.primaryAddress_QLineEdit"), "<Tab>")
    type(waitForObject(":Addresses.city_QLineEdit"), "Hagfors")
    type(waitForObject(":Addresses.city_QLineEdit"), "<Tab>")
    type(waitForObject(":Addresses.state_QLineEdit"), "Värmand")    
    type(waitForObject(":Addresses.state_QLineEdit"), "<Tab>")
    type(waitForObject(":Addresses.postalCode_QLineEdit"), "23456")
    type(waitForObject(":Addresses.postalCode_QLineEdit"), "<Tab>")
    type(waitForObject(":Addresses.country_QLineEdit"), "Sweden")
    type(waitForObject(":Addresses.country_QLineEdit"), "<Tab>")
    type(waitForObject(":Addresses.otherAddress_QLineEdit"), "other on address")
    type(waitForObject(":Addresses.otherAddress_QLineEdit"), "<Tab>")
    type(waitForObject(":Addresses.otherCity_QLineEdit"), "Hagfors")
    type(waitForObject(":Addresses.otherCity_QLineEdit"), "<Tab>")
    type(waitForObject(":Addresses.otherState_QLineEdit"), "Värmland")
    type(waitForObject(":Addresses.otherState_QLineEdit"), "<Tab>")
    type(waitForObject(":Addresses.otherPostalCode_QLineEdit"), "34567")
    type(waitForObject(":Addresses.otherPostalCode_QLineEdit"), "<Tab>")
    type(waitForObject(":Addresses.otherCountry_QLineEdit"), "Sweden")
    mouseClick(waitForObject(":Description:.description_QTextEdit_4"), 79, 57, 0, Qt.LeftButton)
    type(waitForObject(":Description:.description_QTextEdit_4"), "äåöäåöäåö")
    clickButton(waitForObject(":&Contact Details.Save_QPushButton"))
    activateItem(waitForObjectItem(":SugarCRM Client: admin@SugarCRM on localhost.menubar_QMenuBar", "File"))
    activateItem(waitForObjectItem(":SugarCRM Client: admin@SugarCRM on localhost.File_QMenu", "Syncronize"))
    label = waitForObject(':Contact Information.createdBy_QLabel')
    waitFor("label.text !=''")
    # data back from remote client - check Contact's saved data values
    waitFor("object.exists(':Details.salutation_QComboBox_2')")
    test.compare(findObject(":Details.salutation_QComboBox_2").currentText, "Mr\\.")
    waitFor("object.exists(':Details.firstName_QLineEdit_2')")
    test.compare(findObject(":Details.firstName_QLineEdit_2").text, "test")
    waitFor("object.exists(':Details.lastName_QLineEdit_2')")
    test.compare(findObject(":Details.lastName_QLineEdit_2").text, "contact")
    waitFor("object.exists(':Details.title_QLineEdit_2')")
    test.compare(findObject(":Details.title_QLineEdit_2").text, "vd")
    waitFor("object.exists(':Details.department_QLineEdit_2')")
    test.compare(findObject(":Details.department_QLineEdit_2").text, "sales")     
    waitFor("object.exists(':Details.accountName_QComboBox_2')")
    test.compare(findObject(":Details.accountName_QComboBox_2").currentText, "test account")     
    waitFor("object.exists(':Details.leadSource_QComboBox_3')")
    test.compare(findObject(":Details.leadSource_QComboBox_3").currentText, "Employee")
    waitFor("object.exists(':Details.assignedTo_QComboBox')")
    test.compare(findObject(":Details.assignedTo_QComboBox").currentText, "max")
    waitFor("object.exists(':Details.reportsTo_QComboBox')")
    test.compare(findObject(":Details.reportsTo_QComboBox").currentText, "Lynn Ahl")
    waitFor("object.exists(':Details.primaryEmail_QLineEdit')")
    test.compare(findObject(":Details.primaryEmail_QLineEdit").text, "mail@kdab.com")
    waitFor("object.exists(':Other Details.officePhone_QLineEdit')")
    test.compare(findObject(":Other Details.officePhone_QLineEdit").text, "123456")
    waitFor("object.exists(':Other Details.mobilePhone_QLineEdit')")
    test.compare(findObject(":Other Details.mobilePhone_QLineEdit").text, "654321")
    waitFor("object.exists(':Other Details.homePhone_QLineEdit')")
    test.compare(findObject(":Other Details.homePhone_QLineEdit").text, "78906")
    waitFor("object.exists(':Other Details.otherPhone_QLineEdit')")
    test.compare(findObject(":Other Details.otherPhone_QLineEdit").text, "234567")
    waitFor("object.exists(':Other Details.fax_QLineEdit')")
    test.compare(findObject(":Other Details.fax_QLineEdit").text, "876543")
    waitFor("object.exists(':Other Details.birthDate_QLineEdit_2')")
    test.compare(findObject(":Other Details.birthDate_QLineEdit_2").text, "2010-07-05")
    waitFor("object.exists(':Other Details.assistant_QLineEdit')")
    test.compare(findObject(":Other Details.assistant_QLineEdit").text, "mrs untel")
    waitFor("object.exists(':Other Details.assistantPhone_QLineEdit')")
    test.compare(findObject(":Other Details.assistantPhone_QLineEdit").text, "876590")
    waitFor("object.exists(':Addresses.primaryAddress_QLineEdit')")
    test.compare(findObject(":Addresses.primaryAddress_QLineEdit").text, "primary")
    waitFor("object.exists(':Addresses.city_QLineEdit')")
    test.compare(findObject(":Addresses.city_QLineEdit").text, "Hagfors")
    waitFor("object.exists(':Addresses.state_QLineEdit')")
    test.compare(findObject(":Addresses.state_QLineEdit").text, "Värmand")
    waitFor("object.exists(':Addresses.postalCode_QLineEdit')")
    test.compare(findObject(":Addresses.postalCode_QLineEdit").text, "23456")     
    waitFor("object.exists(':Addresses.country_QLineEdit')")
    test.compare(findObject(":Addresses.country_QLineEdit").text, "Sweden")
    waitFor("object.exists(':Addresses.otherAddress_QLineEdit')")
    test.compare(findObject(":Addresses.otherAddress_QLineEdit").text, "other on address")
    waitFor("object.exists(':Addresses.otherCity_QLineEdit')")
    test.compare(findObject(":Addresses.otherCity_QLineEdit").text, "Hagfors")
    waitFor("object.exists(':Addresses.otherState_QLineEdit')")
    test.compare(findObject(":Addresses.otherState_QLineEdit").text, "Värmland")
    waitFor("object.exists(':Addresses.otherPostalCode_QLineEdit')")
    test.compare(findObject(":Addresses.otherPostalCode_QLineEdit").text, "34567")
    waitFor("object.exists(':Addresses.otherCountry_QLineEdit')")
    test.compare(findObject(":Addresses.otherCountry_QLineEdit").text, "Sweden")    
    waitFor("object.exists(':Description:.description_QTextEdit_4')")
    test.compare(findObject(":Description:.description_QTextEdit_4").plainText, "äåöäåöäåö")
    clickButton(waitForObject(":SugarCRM Client: admin@SugarCRM on localhost.Show Details_QCheckBox"))
    mouseClick(waitForObject(":Contacts.searchLE_QLineEdit"), 93, 11, 0, Qt.LeftButton)    
    type(waitForObject(":Contacts.searchLE_QLineEdit"), "test ")
    clickButton(waitForObject(":SugarCRM Client: admin@SugarCRM on localhost.Show Details_QCheckBox"))
    clickTab(waitForObject(":SugarCRM Client: admin@SugarCRM on localhost.qt_tabwidget_tabbar_QTabBar"), "Campaigns")
    # create and save a new Campaign
    clickButton(waitForObject(":Form.New Campaign_QPushButton"))
    mouseClick(waitForObject(":Details.name_QLineEdit_3"), 149, 15, 0, Qt.LeftButton)
    type(waitForObject(":Details.name_QLineEdit_3"), "test campaign")
    mouseClick(waitForObject(":Details.status_QComboBox"), 63, 6, 0, Qt.LeftButton)
    mouseClick(waitForObjectItem(":Details.status_QComboBox", "In Queue"), 35, 0, 0, Qt.LeftButton)
    clickButton(waitForObject(":Details.Edit_EditCalendarButton_2"))
    waitForObjectItem(":Calendar.qt_calendar_calendarview_QCalendarView", "2/2")
    clickItem(":Calendar.qt_calendar_calendarview_QCalendarView", "2/2", 18, 8, 0, Qt.LeftButton)
    clickButton(waitForObject(":Details.Edit_EditCalendarButton_3"))
    waitForObjectItem(":Calendar.qt_calendar_calendarview_QCalendarView", "4/5")
    clickItem(":Calendar.qt_calendar_calendarview_QCalendarView", "4/5", 15, 10, 0, Qt.LeftButton)
    mouseClick(waitForObject(":Details.campaignType_QComboBox"), 68, 12, 0, Qt.LeftButton)
    mouseClick(waitForObjectItem(":Details.campaignType_QComboBox", "Print"), 30, 2, 0, Qt.LeftButton)
    mouseClick(waitForObject(":Details.currency_QComboBox"), 64, 18, 0, Qt.LeftButton)
    mouseClick(waitForObjectItem(":Details.currency_QComboBox", "US Dollars : $"), 59, 4, 0, Qt.LeftButton)
    mouseClick(waitForObject(":Details.budget_QLineEdit"), 52, 13, 0, Qt.LeftButton)
    type(waitForObject(":Details.budget_QLineEdit"), "234567890")
    mouseClick(waitForObject(":Details.expectedRevenue_QLineEdit"), 50, 14, 0, Qt.LeftButton)
    type(waitForObject(":Details.expectedRevenue_QLineEdit"), "345678901")
    mouseClick(waitForObject(":Other Details.assignedUserName_QComboBox"), 37, 16, 0, Qt.LeftButton)
    mouseClick(waitForObjectItem(":Other Details.assignedUserName_QComboBox", "max"), 32, 8, 0, Qt.LeftButton)
    mouseClick(waitForObject(":Other Details.impressions_QLineEdit"), 52, 21, 0, Qt.LeftButton)
    type(waitForObject(":Other Details.impressions_QLineEdit"), "10000")
    mouseClick(waitForObject(":Other Details.actualCost_QLineEdit"), 46, 11, 0, Qt.LeftButton)
    type(waitForObject(":Other Details.actualCost_QLineEdit"), "456789")
    mouseClick(waitForObject(":Other Details.expectedCost_QLineEdit"), 46, 8, 0, Qt.LeftButton)
    type(waitForObject(":Other Details.expectedCost_QLineEdit"), "455789")
    mouseClick(waitForObject(":Other Details.objective_QTextEdit"), 37, 20, 0, Qt.LeftButton)
    type(waitForObject(":Other Details.objective_QTextEdit"), "sales")
    mouseClick(waitForObject(":Description:.content_QTextEdit"), 304, 54, 0, Qt.LeftButton)
    type(waitForObject(":Description:.content_QTextEdit"), "öäåöäåö")
    clickButton(waitForObject(":&Campaign Details.Save_QPushButton"))
    activateItem(waitForObjectItem(":SugarCRM Client: admin@SugarCRM on localhost.menubar_QMenuBar", "File"))
    activateItem(waitForObjectItem(":SugarCRM Client: admin@SugarCRM on localhost.File_QMenu", "Syncronize"))
    label = waitForObject(':Campaign Information.modifiedBy_QLabel')
    waitFor("label.text !=''")
    # data back from remote client - check Campaign's saved data values    
    waitFor("object.exists(':Details.name_QLineEdit_3')")
    test.compare(findObject(":Details.name_QLineEdit_3").text, "test campaign")    
    waitFor("object.exists(':Details.status_QComboBox')")
    test.compare(findObject(":Details.status_QComboBox").currentText, "In Queue")
    waitFor("object.exists(':Details.startDate_QLineEdit')")
    test.compare(findObject(":Details.startDate_QLineEdit").text, "2010-07-05")    
    waitFor("object.exists(':Details.endDate_QLineEdit')")
    test.compare(findObject(":Details.endDate_QLineEdit").text, "2010-07-22")
    waitFor("object.exists(':Details.campaignType_QComboBox')")
    test.compare(findObject(":Details.campaignType_QComboBox").currentText, "Print")
    waitFor("object.exists(':Details.currency_QComboBox')")
    test.compare(findObject(":Details.currency_QComboBox").currentText, "US Dollars : $")
    waitFor("object.exists(':Details.budget_QLineEdit')")
    test.compare(findObject(":Details.budget_QLineEdit").text, "234567890")
    waitFor("object.exists(':Details.expectedRevenue_QLineEdit')")
    test.compare(findObject(":Details.expectedRevenue_QLineEdit").text, "345678901")    
    waitFor("object.exists(':Other Details.assignedUserName_QComboBox')")
    test.compare(findObject(":Other Details.assignedUserName_QComboBox").currentText, "max")
    waitFor("object.exists(':Other Details.impressions_QLineEdit')")
    test.compare(findObject(":Other Details.impressions_QLineEdit").text, "10000")
    waitFor("object.exists(':Other Details.actualCost_QLineEdit')")
    test.compare(findObject(":Other Details.actualCost_QLineEdit").text, "456789")
    waitFor("object.exists(':Other Details.expectedCost_QLineEdit')")
    test.compare(findObject(":Other Details.expectedCost_QLineEdit").text, "455789")
    waitFor("object.exists(':Other Details.objective_QTextEdit')")
    test.compare(findObject(":Other Details.objective_QTextEdit").plainText, "sales")
    waitFor("object.exists(':Description:.content_QTextEdit')")
    test.compare(findObject(":Description:.content_QTextEdit").plainText, "öäåöäåö") 
    clickButton(waitForObject(":SugarCRM Client: admin@SugarCRM on localhost.Show Details_QCheckBox"))
    clickTab(waitForObject(":SugarCRM Client: admin@SugarCRM on localhost.qt_tabwidget_tabbar_QTabBar"), "Accounts")
    activateItem(waitForObjectItem(":SugarCRM Client: admin@SugarCRM on localhost.menubar_QMenuBar", "File"))
    activateItem(waitForObjectItem(":SugarCRM Client: admin@SugarCRM on localhost.File_QMenu", "Quit"))
